
import traceback
from datetime import datetime
from llm_service import LLMInference
from models import ContextData

def test_llm_generation():
    print("=" * 80)
    print("TESTING LLM SERVICE (Phi-3 via Ollama)")
    print("=" * 80)

    try:
        # Initialize the LLM Service
        print("\n[1] Initializing LLMInference...")
        llm_service = LLMInference()
        print("    Success!")

        # Mock Context Data (from ContextService)
        context = ContextData(
            location="123 Lotus Road, Colombo, Sri Lanka",
            time_of_day="2026-05-20 09:30:00",
            weekday=True,
            weather="rainy",
            latitude=6.9271,
            longitude=79.8612
        )

        # Mock Emotion Context (from Logic Engine)
        emotion_context = {
            "current_emotion": "stressed",
            "duration_minutes": 15,
            "include_previous": True,
            "previous_emotion": "neutral",
            "minutes_since_change": 15
        }

        print("\n[2] Generating Feedback...")
        print(f"    Emotion: {emotion_context['current_emotion']} (for {emotion_context['duration_minutes']} mins)")
        print(f"    Context: {context.location} | {context.weather}")
        
        response = llm_service.generate_feedback(emotion_context, context)

        print("\n[3] Result:")
        print("-" * 40)
        print(response.message)
        print("-" * 40)
        print(f"Timestamp: {response.timestamp}")
        
        if response.emotion_context == "error_fallback":
            print("\n❌ FAILURE: Model generation failed (Fallback used). check if Ollama is running.")
        else:
            print("\n✅ SUCCESS: Feedback generated by Phi-3 model.")


    except Exception as e:
        print(f"\n❌ CRITICAL ERROR: {e}")
        traceback.print_exc()

if __name__ == "__main__":
    test_llm_generation()
